name: rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@just
      
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: build since clippy needs contracts to be built
        run: just build
      - name: Run cargo clippy
        run: cargo clippy --all
      - name: Unit Tests
        run: just test
